---
# defaults/main.yml - Safe Default Values

### Core Hardening Settings ###
hardening_level: "high" # [low|medium|high]
enable_fips: false
auditd_enabled: true

### System Configuration ###
# Kernel hardening
kernel_settings:
  kernel.yama.ptrace_scope: 1
  kernel.kptr_restrict: 2
  net.ipv4.conf.all.rp_filter: 1

# Filesystem protections
mount_options:
  /tmp: "noexec,nosuid,nodev"
  /var/tmp: "noexec,nosuid,nodev,bind"

### User Authentication ###
pam_settings:
  password:
    minlen: 12
    difok: 5
    remember: 5
  faillock:
    deny: 5
    unlock_time: 900

### Docker Security Defaults ###
docker_required: false
docker_config:
  icc: false
  userns_remap: "default"
  no_new_privileges: true
  seccomp_profile: "/etc/docker/seccomp/default.json"
  log_level: "info"
  log_driver: "json-file"
  log_opts:
    max-size: "10m"
    max-file: "3"

### Container Security Policies (Task 1.2) ###
docker_network_hardening: true
dns_allowed_ips: ["172.17.0.2"] # Default to Docker DNS

# Resource Controls
container_resource_limits:
  cpu_quota: 50000 # 50% of CPU
  memory: "512m"
  pids: 100
  blkio_weight: 500

# Image Security
content_trust_enabled: false
required_image_labels:
  - "org.opencontainers.image.vendor"
  - "org.opencontainers.image.source"
  - "org.opencontainers.image.version"

# Access Controls
docker_rbac_enabled: true
docker_audit_level: "info" # [info|warn|error]

### Compliance Profiles ###
compliance:
  cis:
    profile: "hardened" # [server|l1|l2|hardened]
  im8:
    enabled: false
    profile: "essential" # [essential|enhanced|financial]
  nist:
    level: "moderate" # [low|moderate|high]

### Safe Service Defaults ###
disabled_services:
  - rpcbind
  - avahi-daemon
  - cups
enabled_services:
  - auditd
  - sshd
