---
- name: Ensure base directories exist
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - /etc/periodic/daily
    - /home/{{ admin_user }}/.ssh

- name: Set timezone (Asia/Singapore)
  timezone:
    name: "{{ timezone }}"

- name: Install base packages
  apk:
    name: "{{ base_packages }}"
    state: present
    update_cache: yes

- name: Update all packages
  apk:
    upgrade: yes
