---
# inventory/production/group_vars/container_host.yml
# Unified Docker Host Configuration

### Base Inherited Settings ###
hardening_level: "high"
enable_fips: false
auditd_enabled: true

### Docker Daemon Configuration ###
docker_icc_enabled: false
docker_userns: "dockremap"
docker_no_new_privileges: true
docker_seccomp_profile: "/etc/docker/seccomp/hardened.json"
docker_apparmor_profile: "docker-hardened"
docker_log_driver: "json-file"
docker_log_opts:
  max-size: "10m"
  max-file: "3"
docker_default_ulimits:
  nofile: 64000 # Increased from your 1024 for production
docker_selinux_enabled: true

### Container Runtime Requirements ###
container_requirements:
  non_root: true
  readonly_rootfs: false
  healthchecks:
    test: ["CMD-SHELL", "/bin/check-health"]
    interval: "30s"
    timeout: "5s"
    retries: 3
  capabilities:
    drop: ["ALL"]
    add: ["CHOWN", "NET_BIND_SERVICE"]

### Network Security ###
docker_iptables: true
docker_default_network: "bridge"
docker_dns_servers:
  - "8.8.8.8"
  - "8.8.4.4"

### Compliance Mappings ###
compliance:
  cis:
    profile: "hardened"
    docker_profile: "l2"
  im8:
    enabled: true
    profile: "enhanced"
    docker_controls: ["4.1", "4.5", "6.2"]
  nist:
    level: "moderate"
    controls: ["AC-6", "SC-7", "SI-4", "SI-7"] # Added SI-7

### Monitoring ###
logging:
  docker_driver: "syslog"
  syslog_address: "udp://logcollector.example.com:514"
  audit_rules:
    - "-w /usr/bin/docker -p x -k docker_cli"
    - "-a always,exit -F path=/usr/bin/containerd -F perm=x -k container_runtime"
    - "-w /etc/docker/daemon.json -p wa -k docker_config" # Added
