version: "3.8"

services:
  #created-in: docker stack deploy -c 01.2-persist.yml persist
  local-persist:
    image: cwspear/docker-local-persist-volume-plugin:latest
    volumes:
      - /run/docker/plugins/:/run/docker/plugins/:rw
      - /opt/json/:/var/lib/docker/plugin-data/:rw
    environment:
      - PUID:1001
      - PGID:1001
    deploy:
      mode: global
      placement:
        max_replicas_per_node: 1
      update_config:
        parallelism: 1
    labels:
      - "deunhealth.restart.on.unhealthy=true"
