version: "3.8"

services:
  deunhealth:
    image: qmcgaw/deunhealth
    container_name: deunhealth
    restart: unless-stopped
    depends_on:
      - persist_local-persist
    deploy:
      mode: global
      placement:
        max_replicas_per_node: 1
      update_config:
        parallelism: 1
    environment:
      - LOG_LEVEL=info
      - HEALTH_SERVER_ADDRESS=127.0.0.1:9999
      - TZ=Asia/Singapore
      - PUID:1001
      - PGID:1001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "deunhealth.restart.on.unhealthy=true"
