version: '3.2'

services:

  agent:
    image: portainer/agent:lastest
    deploy:
      mode: global
    networks:
      - agent_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes

  portainer:
    image: portainer/portainer:latest
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.name == unison-master]
    networks:
      - agent_network
    ports:
      - "10053:9443"
      - "9000:9000"
      #- "8000:8000"
    volumes:
      - /mnt/portainer_data:/data
    command: -H tcp://tasks.agent:9001 --tlsskipverify

networks:
  agent_network:
    driver: overlay
    attachable: true

volumes:
  portainer_data:
