version: '3.8'
  #docker secret create ganjaking.cloud.sslcert /mnt/certs/ganjaking.cloud.sslcert
  #docker secret create ganjaking.cloud.sslkey /mnt/certs/ganjaking.cloud.sslkey
  #docker secret create ganjaking.cloud.cacert /mnt/certs/ganjaking.cloud.cacert
services:

  agent:
    image: portainer/agent:2.9.2
    deploy:
      mode: global
    networks:
      - agent_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/volumes:/var/lib/docker/volumes
    ports:
      - target: 9001
        published: 9001
        protocol: tcp
        mode: host

  portainer:
    image: portainer/portainer-ce:2.9.2
    deploy:
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints: [node.labels.name == unison-master]
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s
      update_config:
        parallelism: 1
        delay: 5s
        order: stop-first
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    networks:
      - agent_network
    ports:
      - "10053:9443"
      - "9000:9000"
      #- "8000:8000"
    volumes:
      - /mnt/portainer_data:/data
    command: -H tcp://tasks.agent:9001 --tlsskipverify

networks:
  agent_network:
    driver: overlay
    attachable: true

volumes:
  portainer_data:
