version: '3.8'

services:
  #created-in: docker stack deploy -c 01.0-portainer.yml portainer
  portainer:
    image: portainer/portainer-ee:latest
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.name == unison-master]
    ports:
      - "10051:9443"
    volumes:
      - /mnt/portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - portainer_default
    labels:
      - "deunhealth.restart.on.unhealthy=true"

networks:
  portainer_default:
    driver: overlay
    attachable: true