version: "3.8"

services:
  portainer:
    image: portainer/portainer-ce:2.20.2 # Pinned version (replace with latest stable)
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.name == dns-master]
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: "1"
          memory: 512M
        reservations:
          memory: 256M
    ports:
      - "10050:9443" # HTTPS access (consider firewall rules)
    volumes:
      - portainer_data:/data:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro # Read-only socket
    networks:
      - portainer_net
    healthcheck:
      test: ["CMD", "curl", "-fks", "https://localhost:9443/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"

  # Portainer Agent (Cluster Communication)
  agent:
    image: portainer/agent:2.20.2
    deploy:
      mode: global # Runs on every node
      resources:
        limits:
          cpus: "0.2"
          memory: 256M
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - portainer_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/ping"]
      interval: 10s
      timeout: 3s

networks:
  portainer_net:
    driver: overlay
    attachable: false # Disallow external connections
    labels:
      - "maintained_by=DevOps"
      - "purpose=portainer_management"

volumes:
  portainer_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/portainer_data
# Uncomment if using secrets (e.g., for admin password):
# secrets:
#   portainer_admin_password:
#     external: true
