version: '3.8'

services:
#created-in: docker stack deploy -c 01.0-powerdns.yml pdns
  mysqldb:
    image: mariadb:latest
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.name == dns-master]
      restart_policy:
        condition: on-failure
    ports:
      - "3306:3306"
    volumes:
      - /opt/mysql_db:/var/lib/mysql
    networks:
      - default
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${MYSQL_PASSWORD}
    labels:
      - "deunhealth.restart.on.unhealthy=true"

  phpmyadmin:
    image: phpmyadmin:latest
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.name == dns-master]
      restart_policy:
        condition: on-failure
    ports:
      - "8079:80"
    networks:
      - default
    environment:
      - PM_ARBITRARY=1
      - PMA_HOST=mysqldb

  pdns:
    image: pschiffe/pdns-mysql:latest
    hostname: dns.ganjaking.cloud
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.name == dns-master]
      restart_policy:
        condition: on-failure
    depends_on:
      - mysqldb
    links:
      - "mysqldb:mysql"
    ports:
      - "53:53"
      - "53:53/udp"
      - "8081:8081"
    networks:
      - default
    environment:
      - PDNS_gmysql_host=mysqldb
      - PDNS_gmysql_port=3306
      - PDNS_gmysql_user=${MYSQL_USER}
      - PDNS_gmysql_dbname=${MYSQL_DATABASE}
      - PDNS_gmysql_password=${MYSQL_PASSWORD}
      - PDNS_master=yes
      - PDNS_api=yes
      - PDNS_api_key=${PDNS_API_KEY}
      - PDNSCONF_API_KEY={$PDNS_API_CONF_KEY}
      - PDNS_webserver=yes
      - PDNS_webserver-allow-from=127.0.0.1,10.0.0.0/8,172.0.0.0/8,192.0.0.0/24
      - PDNS_webserver_address=0.0.0.0
      - PDNS_webserver_password=${PDNS_PASSWORD}
      - PDNS_version_string=anonymous
      - PDNS_default_ttl=1500
      - PDNS_allow_notify_from=0.0.0.0
      - PDNS_allow_axfr_ips=127.0.0.1

  pdns_admin:
    image: powerdnsadmin/pda-legacy:latest
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.name == dns-master]
      restart_policy:
        condition: on-failure
    ports:
      - "8080:80"
    networks:
      - default
    depends_on:
      - mysqldb
    restart: always
    links:
      - mysqldb:mysql
      - pdns:pdns
    logging:
      driver: json-file
      options:
        max-size: 50m
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysqldb/${MYSQL_DATABASE}
      - GUNICORN_TIMEOUT=60
      - GUNICORN_WORKERS=2
      - GUNICORN_LOGLEVEL=DEBUG
      - GUNICORN_LOG_LEVEL=WARN
      - LOG_LEVEL=WARN
      - OFFLINE_MODE=False

  nginxproxymanager:
    image: jc21/nginx-proxy-manager:2.10.3
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.labels.name == dns-master ]
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    networks:
      - default
    depends_on:
      - mysqldb
    restart: always
    links:
      - mysqldb:mysql
    volumes:
      - /opt/nginx-proxy-manager/data/:/data:rw
      - /opt/nginx-proxy-manager/ssl/:/etc/letsencrypt:rw
    environment:
      - DB_MYSQL_HOST=mysqldb
      - DB_MYSQL_PORT=3306
      - DB_MYSQL_USER=${MYSQL_USER}
      - DB_MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - DB_MYSQL_NAME=${MYSQL_DATABASE_NGINX}