version: '3.8'

services:
  pmm-server:
    image: percona/pmm-server:2
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 60s
        max_failure_ratio: 0.3
    networks:
      - default
    ports:
      - "8082:80"
    ulimits:
      memlock: 67108864
    volumes:
      - /opt/pmm_data:/srv:rw

  pmm-client:
    image: percona/pmm-client:2
    deploy:
      mode: global
      placement:
        max_replicas_per_node: 1
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 60s
        max_failure_ratio: 0.3
    networks:
      - default
    environment:
      PMM_AGENT_SERVER_ADDRESS: "pmm-server"
      PMM_AGENT_SERVER_USERNAME: ${PMM_AGENT_SERVER_USERNAME}
      PMM_AGENT_SERVER_PASSWORD: ${PMM_AGENT_SERVER_PASSWORD}
      PMM_AGENT_SERVER_INSECURE_TLS: "1"
      PMM_AGENT_SETUP: "1"
      PMM_AGENT_CONFIG_FILE: "config/pmm-agent.yaml"
    volumes:
      - /opt/pmm_client_data:/srv:rw