version: '3.8'

services:
  #created-in: docker stack deploy -c 01.0-portainer.yml porta
  agent:
    image: portainer/agent:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/volumes:/var/lib/docker/volumes:rw
    networks:
      - ws
    deploy:
      mode: global
      placement:
        max_replicas_per_node: 1
    ports:
      - "9001:9001"
    environment:
       AGENT_CLUSTER_ADDR: tasks.agent
       AGENT_PORT: 9001
       LOG_LEVEL: DEBUG

  portainer:
    image: portainer/portainer-ee:latest
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.name == unison-master]
      labels:
        traefik.enable: "true"
        traefik.docker.network: "internet"
        traefik.http.routers.portainer.entrypoints: "https"
        traefik.http.routers.portainer.middlewares: "default@file"
        traefik.http.routers.portainer.rule: "Host(`cluster.ganjaking.cloud`)"
        traefik.http.routers.portainer.tls.options: "modern@file"
        traefik.http.routers.portainer.tls: "true"
        traefik.http.services.portainer.loadbalancer.server.port: 9000
        traefik.http.services.portainer.loadbalancer.sticky.cookie.httpOnly: "true"
        traefik.http.services.portainer.loadbalancer.sticky.cookie.secure: "true"
    volumes:
      - /opt/portainer_data:/data:rw
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ws
      - internet

networks:
  ws:
    driver: overlay
    attachable: true
  internet:
    external: true
    attachable: true

volumes:
  portainer_data:
    driver_opts:
      mountpoint: /opt/portainer_data