version: '3.8'

services:
#created-in: docker stack deploy -c 01.0-powerdns.yml portal
  mysqldb:
    image: maridb:lastest
    restart: always
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.name == dns-master]
    ports:
      - "3306:3306"
    volumes:
      - /opt/mysql_db: /var/lib/mysql
    networks:
      - portal_default
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    labels:
      - "deunhealth.restart.on.unhealthy=true"

  pdns:
    image: pschiffe/pdns-mysql:latest
    restart: always
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraint: [node.labels.name == dns-master]
    hostname: pdns
    domainname: ${DOMAINNAME}
    depends_on:
      - mysqldb
    links:
      - "mysqldb:mysql"
    ports:
      - "53:53"
      - "53:53/udp"
      - "8081:8081"
    networks:
      - portal_default
    environment:
      - PDNS_gmysql_host=mysqldb
      - PDNS_gmysql_port=3306
      - PDNS_gmysql_user=${MYSQL_USER}
      - PDNS_gmysql_dbname=${MYSQL_DATABASE}
      - PDNS_gmysql_password=${MYSQL_PASSWORD}
      - PDNS_master=yes
      - PDNS_api=yes
      - PDNS_api_key=${PDNS_API_KEY}
      - PDNSCONF_API_KEY={$PDNS_API_CONF_KEY}
      - PDNS_webserver=yes
      - PDNS_webserver_address=0.0.0.0
      - PDNS_webserver_password=${PDNS_PASSWORD}
      - PDNS_version_string=anonymous
      - PDNS_default_ttl=1500
      - PDNS_allow_notify_from=0.0.0.0
      - PDNS_allow_axfr_ips=127.0.0.1

  pdns_admin:
    image: powerdnsadmin/pda-legacy:lastest
    restart: always
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.name == dns-master]
    ports:
      - "8080:80"
    networks:
      - portal_default
    depends_on:
      - mysqldb
    restart: always
    links:
      - mysqldb:mysql
      - pdns:pdns
    logging:
      driver: json-file
      options:
        max-size: 50m
    environment:
      - SSQLALCHEMY_DATABASE_URI=mysqldb://pdns:${MYSQL_PASSWORD}@mysql/${MYSQL_DATABASE}
      - GUNICORN_TIMEOUT=60
      - GUNICORN_WORKERS=2
      - GUNICORN_LOGLEVEL=DEBUG

