version: '3.8'

services:
  #created-in: docker stack deploy -c 01.0-portainer.yml porta
  agent:
    image: portainer/agent:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/volumes:/var/lib/docker/volumes:rw
    ports:
      - target: 9001
        published: 9001
        protocol: tcp
        mode: host
    networks:
      - websecured
    deploy:
      mode: global
      placement:
        max_replicas_per_node: 1
      update_config:
        parallelism: 1

  portainer:
    image: portainer/portainer-ee:latest
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.name == unison-master]
    ports:
      - "10050:9443"
      #- "9000:9000"
      #- "8000:8000"
    volumes:
      - /opt/portainer_data:/data:rw
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - websecured

networks:
  websecured:
    driver: overlay
    attachable: true

volumes:
  portainer_data:
    driver_opts:
      mountpoint: /opt/portainer_data