version: '3.8'

services:
#created-in: docker stack deploy -c 01.1-portainer-agent.yml porta
  agent:
    image: portainer/agent:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/volumes:/var/lib/docker/volumes:rw
    ports:
      - target: 9001
        published: 9001
        protocol: tcp
        mode: host
    networks:
      - default
    deploy:
      mode: global
      placement:
        max_replicas_per_node: 1
      update_config:
        parallelism: 1
    labels:
      - "deunhealth.restart.on.unhealthy=true"

networks:
  default:
    driver: overlay
    attachable: true