version: '3.8'

services:

  node-master:
    image: docker.io/bitnami/minio:2021
    user: '0:0'
    ports:
      - "9000:9000"
      - "10052:9001"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.name == unison-master]
    volumes:
      - '/opt:/data'
      - '/opt/certs:/certs'
    environment:
      - 'MINIO_ROOT_USER=/run/secrets/MINIO_ROOT_USER'
      - 'MINIO_ROOT_PASSWORD=/run/secrets/MINIO_ROOT_PASSWORD'
      - 'MINIO_DISTRIBUTED_MODE_ENABLED=yes'
      - 'MINIO_DISTRIBUTED_NODES=node-master,node-0,node-1,node-2'

  node-0:
    image: docker.io/bitnami/minio:2021
    user: '0:0'
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.labels.name == unison-node-0 ]
    volumes:
      - '/opt:/data'
      - '/opt/certs:/certs'
    environment:
      - 'MINIO_ROOT_USER=/run/secrets/MINIO_ROOT_USER'
      - 'MINIO_ROOT_PASSWORD=/run/secrets/MINIO_ROOT_PASSWORD'
      - 'MINIO_DISTRIBUTED_MODE_ENABLED=yes'
      - 'MINIO_DISTRIBUTED_NODES=node-master,node-0,node-1,node-2'

  node-1:
    image: docker.io/bitnami/minio:2021
    user: '0:0'
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.labels.name == unison-node-1 ]
    volumes:
      - '/opt:/data'
      - '/opt/certs:/certs'
    environment:
      - 'MINIO_ROOT_USER=/run/secrets/MINIO_ROOT_USER'
      - 'MINIO_ROOT_PASSWORD=/run/secrets/MINIO_ROOT_PASSWORD'
      - 'MINIO_DISTRIBUTED_MODE_ENABLED=yes'
      - 'MINIO_DISTRIBUTED_NODES=node-master,node-0,node-1,node-2'

  node-2:
    image: docker.io/bitnami/minio:2021
    user: '0:0'
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.labels.name == unison-node-2 ]
    volumes:
      - '/opt:/data'
      - '/opt/certs:/certs'
    environment:
      - 'MINIO_ROOT_USER=/run/secrets/MINIO_ROOT_USER'
      - 'MINIO_ROOT_PASSWORD=/run/secrets/MINIO_ROOT_PASSWORD'
      - 'MINIO_DISTRIBUTED_MODE_ENABLED=yes'
      - 'MINIO_DISTRIBUTED_NODES=node-master,node-0,node-1,node-2'