version: '3.8'

services:

  agent:
    image: portainer/agent:2.10.0-alpine
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/volumes:/var/lib/docker/volumes:rw
    ports:
      - target: 9001
        published: 9001
        protocol: tcp
        mode: host
    networks:
      - portainer_default
    deploy:
      mode: global
      placement:
        max_replicas_per_node: 1
      update_config:
        parallelism: 1
    labels:
      - "deunhealth.restart.on.unhealthy=true"
networks:
  portainer_default:
    driver: overlay
    attachable: true