version: '3.8'

services:

  local-persist:
    image: cwspear/docker-local-persist-volume-plugin:latest
    volumes:
      - /run/docker/plugins/:/run/docker/plugins/:rw
      - /opt/json/:/var/lib/docker/plugin-data/:rw
    deploy:
      mode: global
      placement:
        max_replicas_per_node: 1
      update_config:
        parallelism: 1
    labels:
      - "deunhealth.restart.on.unhealthy=true"