version: "3.8"

services:
  syncthing-master:
    image: syncthing/syncthing:latest
    networks:
      - sync
      - internet
    volumes:
      - sync:/var/syncthing:rw
    environment:
      PUID: "1001"
      PGID: "1001"
    ports:
      - target: 8384
        published: 10052
        protocol: tcp
        mode: host
      - target: 22000
        published: 22000
        protocol: tcp
        mode: host
      - target: 22000
        published: 22000
        protocol: udp
        mode: host
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.labels.name == unison-master ]
    labels:
      - "deunhealth.restart.on.unhealthy=true"

  syncthing-node-0:
    image: syncthing/syncthing:latest
    networks:
      - sync
      - internet
    volumes:
      - sync:/var/syncthing:rw
    environment:
      PUID: "1001"
      PGID: "1001"
    ports:
      - target: 8384
        published: 10052
        protocol: tcp
        mode: host
      - target: 22000
        published: 22000
        protocol: tcp
        mode: host
      - target: 22000
        published: 22000
        protocol: udp
        mode: host
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.labels.name == unison-node-0 ]
    labels:
      - "deunhealth.restart.on.unhealthy=true"

  syncthing-node-1:
    image: syncthing/syncthing:latest
    networks:
      - sync
      - internet
    volumes:
      - sync:/var/syncthing:rw
    environment:
      PUID: "1001"
      PGID: "1001"
    ports:
      - target: 8384
        published: 10052
        protocol: tcp
        mode: host
      - target: 22000
        published: 22000
        protocol: tcp
        mode: host
      - target: 22000
        published: 22000
        protocol: udp
        mode: host
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.labels.name == unison-node-1 ]
    labels:
      - "deunhealth.restart.on.unhealthy=true"

volumes:
  sync:
    driver: local-persist
    driver_opts:
      mountpoint: /opt/sync

networks:
  sync:
    driver: overlay
    attachable: true
  internet:
    external: true
    attachable: true