version: '3.8'

services:

  minio-master:
    image: docker.io/bitnami/minio:latest
    ports:
      - "10052:9000"
      - "9002:9001"
    volumes:
      - /opt/:/data:rw
    networks:
      - minio
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.name == unison-master]
        max_replicas_per_node: 1
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_SKIP_CLIENT: "yes"
      MINIO_DISTRIBUTED_MODE_ENABLED: "yes"
      MINIO_DISTRIBUTED_NODES: "minio-master,minio-node-0,minio-node-1,minio-node-2"
    depends_on:
      - prepare-data
    labels:
      - "deunhealth.restart.on.unhealthy=true"

  minio-node-0:
    image: docker.io/bitnami/minio:latest
    ports:
      - "9005:9000"
    volumes:
      - /opt/:/data:rw
    networks:
      - minio
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.name == unison-node-0]
        max_replicas_per_node: 1
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_SKIP_CLIENT: "yes"
      MINIO_DISTRIBUTED_MODE_ENABLED: "yes"
      MINIO_DISTRIBUTED_NODES: "minio-master,minio-node-0,minio-node-1,minio-node-2"
    labels:
      - "deunhealth.restart.on.unhealthy=true"

  minio-node-1:
    image: docker.io/bitnami/minio:latest
    ports:
      - "9006:9000"
    volumes:
      - /opt/:/data:rw
    networks:
      - minio
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.name == unison-node-1]
        max_replicas_per_node: 1
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_SKIP_CLIENT: "yes"
      MINIO_DISTRIBUTED_MODE_ENABLED: "yes"
      MINIO_DISTRIBUTED_NODES: "minio-master,minio-node-0,minio-node-1,minio-node-2"
    labels:
      - "deunhealth.restart.on.unhealthy=true"

  minio-node-2:
    image: docker.io/bitnami/minio:latest
    ports:
      - "9007:9000"
    volumes:
      - /opt/:/data:rw
    networks:
      - minio
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.name == unison-node-2]
        max_replicas_per_node: 1
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_SKIP_CLIENT: "yes"
      MINIO_DISTRIBUTED_MODE_ENABLED: "yes"
      MINIO_DISTRIBUTED_NODES: "minio-master,minio-node-0,minio-node-1,minio-node-2"
    labels:
      - "deunhealth.restart.on.unhealthy=true"

networks:
  minio:
    driver: overlay
    attachable: true

volumes:
  certs:
    driver: local-persist
    driver_opts:
      mountpoint: /opt/certs