version: '3.8'

services:
  prepare-data:
    image: 'docker.io/bitnami/bitnami-shell:latest'
    command:
      - /bin/bash
      - -ec
      - |
        chmod -R g+rwX /opt

  minio-master:
    image: docker.io/bitnami/minio:2021
    ports:
      - "10053:9000"
      - "9001:9001"
    volumes:
      - /opt/:/data:rw
    networks:
      - minio
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.lables.name == unison-master]
        max_replicas_per_node: 1
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_SKIP_CLIENT: "yes"
      MINIO_DISTRIBUTED_MODE_ENABLED: "yes"
      MINIO_DISTRIBUTED_NODES: "minio-master,minio-node-0,minio-node-1,minio-node-2"
    depends_on:
      - prepare-data
    labels:
      - "deunhealth.restart.on.unhealthy=true"

  minio-node-0:
    image: docker.io/bitnami/minio:2021
    volumes:
      - /opt/:/data:rw
    networks:
      - minio
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.lables.name == unison-node-0]
        max_replicas_per_node: 1
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_SKIP_CLIENT: "yes"
      MINIO_DISTRIBUTED_MODE_ENABLED: "yes"
      MINIO_DISTRIBUTED_NODES: "minio-master,minio-node-0,minio-node-1,minio-node-2"
    labels:
      - "deunhealth.restart.on.unhealthy=true"

  minio-node-1:
    image: docker.io/bitnami/minio:2021
    volumes:
      - /opt/:/data:rw
    networks:
      - minio
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.lables.name == unison-node-1]
        max_replicas_per_node: 1
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_SKIP_CLIENT: "yes"
      MINIO_DISTRIBUTED_MODE_ENABLED: "yes"
      MINIO_DISTRIBUTED_NODES: "minio-master,minio-node-0,minio-node-1,minio-node-2"
    labels:
      - "deunhealth.restart.on.unhealthy=true"

  minio-node-2:
    image: docker.io/bitnami/minio:2021
    volumes:
      - /opt/:/data:rw
    networks:
      - minio
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.lables.name == unison-node-2]
        max_replicas_per_node: 1
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_SKIP_CLIENT: "yes"
      MINIO_DISTRIBUTED_MODE_ENABLED: "yes"
      MINIO_DISTRIBUTED_NODES: "minio-master,minio-node-0,minio-node-1,minio-node-2"
    labels:
      - "deunhealth.restart.on.unhealthy=true"

networks:
  minio:
    driver: overlay
    attachable: true

volumes:
