version: '3.8'

services:
  authelia:
    image: authelia/authelia:latest
    restart: unless-stopped
    depends_on:
      - local-persist
      - traefik
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.name == unison-master]
      update_config:
        parallelism: 1
    networks:
      - traefik_proxy
    ports:
      - target: 9091
        published: 9091
        protocol: tcp
        mode: host
    volumes:
      - authelia_data: /config
    environment:
      - TZ= Asia/Singapore
    healthcheck:
      disable: true
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.authelia.rule=Host(`auth.ganjaking.cloud)'
      - 'traefik.http.routers.authelia.entrypoints=https'
      - 'traefik.http.routers.authelia.tls=true'
      - 'traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://auth.ganjaking.cloud'
      - 'traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true'
      - 'traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email'

networks:
  traefik_proxy:
    attachable: true
    external: true

volumes:
  authelia_data:
    driver: local-persist
    driver_opts:
      mountpoint: /opt/sync/dk/authelia_data