version: "3.9"
networks:
  internet:
    external: true
    attachable: true

services:
  crowdsec:
    image: crowdsecurity/crowdsec:latest
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.labels.name == unison-master ]
      update_config:
        parallelism: 1
    networks:
      - internet
    volumes:
    - /opt/sync/db/crowdsec_config/acquis.yaml:/etc/crowdsec/acquis.yaml
    - crowdsec_db:/var/lib/crowdsec/data/
    - crowdsec_config:/etc/crowdsec/
    - traefik_data_cd:/var/log/traefik/:ro
    - /opt/sync/db/authelia_data/authelia.log:/config/authelia.log
    environment:
      UID: "1001"
      GID: "1001"
      COLLECTIONS: "crowdsecurity/linux crowdsecurity/traefik LePresidente/authelia"

  bouncer-traefik:
    image: docker.io/fbonalair/traefik-crowdsec-bouncer:latest
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.labels.name == unison-master ]
      update_config:
        parallelism: 1
    networks:
      - internet
    depends_on: [ crowdsec ]
    environment:
      CROWDSEC_BOUNCER_API_KEY: ${CROWDSEC_BOUNCER_API_KEY}
      CROWDSEC_AGENT_HOST: crowdsec:8080

volumes:
  crowdsec_config:
    driver: local-persist
    driver_opts:
      mountpoint: /opt/sync/db/crowdsec_config
  crowdsec_db:
    driver: local-persist
    driver_opts:
      mountpoint: /opt/sync/db/crowdsec_db
  traefik_data_cd:
    driver: local-persist
    driver_opts:
      mountpoint: /opt/sync/db/traefik_data/logs

