version: "3.8"

services:
  #created-in: portainer
  dockergc:
    image: clockworksoul/docker-gc-cron:latest
    depends_on:
      - utilz_local-persist
    deploy:
      mode: global
      placement:
        max_replicas_per_node: 1
      update_config:
        parallelism: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/docker-gc/docker-gc-exclude:/etc/docker-gc-exclude:rw
    environment:
      - CRON=59 23 * * 6
      - FORCE_IMAGE_REMOVAL=1
      - FORCE_CONTAINER_REMOVAL=1
      - MINIMUM_IMAGES_TO_SAVE=1
      - GRACE_PERIOD_SECONDS=3600
      - DRY_RUN=0
      - CLEAN_UP_VOLUMES=1
      - TZ=Asia/Singapore
    labels:
      - "deunhealth.restart.on.unhealthy=true"