version: "3.8"

services:
  #created-in: portainer
  logrotate:
    image: blacklabelops/logrotate:latest
    deploy:
      mode: global
      placement:
        max_replicas_per_node: 1
      update_config:
        parallelism: 1
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers
      - /var/log/messages:/var/log/messages
      - /mnt/logrotate_data:/logs
      - /mnt/logrotate_data/logrotate-status:/logrotate-status
    environment:
      - LOGS_DIRECTORIES=/var/lib/docker/containers /var/log/docker
      - LOG_FILE_ENDINGS=log json xml
      - LOGROTATE_INTERVAL=weekly
      - LOGROTATE_STATUSFILE=/logs/logrotate.status
      - LOGROTATE_SIZE=30M
      - LOGROTATE_COPIES=2
      - LOGROTATE_COMPRESSION=compress
      - LOGROTATE_OLDDIR=/logs
      - LOGROTATE_LOGFILE=/logs/logrotatecron.log
      - LOGROTATE_PARAMETERS=vf
      - LOGROTATE_MAXAGE=60
      - LOGROTATE_MINSIZE=100k
      - TZ=Asia/Singapore
      #- LOGROTATE_CRONSCHEDULE=* * * * * *
