version: '3.8'

services:
  #created-in: portainer
  redis-node-0:
    image: docker.io/bitnami/redis-cluster:latest
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.name == unison-node-0]
        max_replicas_per_node: 1
    volumes:
      - redis-cluster_data-0:/bitnami/redis/data:rw
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_NODES: "redis_redis-node-0 redis_redis-node-1 redis_redis-node-2 redis_redis-master"
    labels:
      - "deunhealth.restart.on.unhealthy=true"

  redis-node-1:
    image: docker.io/bitnami/redis-cluster:latest
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.name == unison-node-1]
        max_replicas_per_node: 1
    volumes:
      - redis-cluster_data-1:/bitnami/redis/data:rw
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_NODES: "redis_redis-node-0 redis_redis-node-1 redis_redis-node-2 redis_redis-master"
    labels:
      - "deunhealth.restart.on.unhealthy=true"

  redis-node-2:
    image: docker.io/bitnami/redis-cluster:latest
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.name == unison-node-2]
        max_replicas_per_node: 1
    volumes:
      - redis-cluster_data-2:/bitnami/redis/data:rw
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_NODES: "redis_redis-node-0 redis_redis-node-1 redis_redis-node-2 redis_redis-master"
    labels:
      - "deunhealth.restart.on.unhealthy=true"

  redis-master:
    image: docker.io/bitnami/redis-cluster:latest
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.name == unison-master]
        max_replicas_per_node: 1
    volumes:
      - redis_cluster_data_master:/bitnami/redis/data
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDISCLI_AUTH: ${REDISCLI_AUTH}
      REDIS_CLUSTER_REPLICAS: "1"
      REDIS_NODES: "redis_redis-node-0 redis_redis-node-1 redis_redis-node-2 redis_redis-master"
      REDIS_CLUSTER_CREATOR: "yes"
      REDIS_DISABLE_COMMANDS: "FLUSHDB,FLUSHALL,CONFIG"
    labels:
      - "deunhealth.restart.on.unhealthy=true"

volumes:
  redis_cluster_data_master:
    driver: local-persist
    driver_opts:
      mountpoint: /opt/sync/dk/redis_cluster_data_master
  redis-cluster_data-0:
    driver: local-persist
    driver_opts:
      mountpoint: /opt/sync/dk/redis-cluster_data-0
  redis-cluster_data-1:
    driver: local-persist
    driver_opts:
      mountpoint: /opt/sync/dk/redis-cluster_data-1
  redis-cluster_data-2:
    driver: local-persist
    driver_opts:
      mountpoint: /opt/sync/dk/redis-cluster_data-2