version: '3.8'

services:
  #created-in: portainer
  traefik:
    image: traefik:latest
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.name == unison-master]
      update_config:
        parallelism: 1
    environment:
      #- CF_API_EMAIL=${CLOUDFLARE_EMAIL}
      #- CF_API_KEY=${CLOUDFLARE_API_KEY}
      - GCE_PROJECT= ${GCE_PROJECT}
      #- GCE_SERVICE_ACCOUNT=/run/secrets/gcp_service_account
      - "GCE_SERVICE_ACCOUNT_FILE=/opt/sync/dk/traefik_data/gcloud.json:/gcloud.json"
  networks:
      - traefik_proxy
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - /opt/sync/dk/traefik_data/traefik.yml:/traefik.yml:ro
      - /opt/sync/dk/traefik_data/acme.json:/acme.json:ro
      - /opt/sync/dk/traefik_data/config.yml:/config.yml:ro
      #- /opt/sync/dk/traefik_data/log/traefik.log:/traefik.log
      #- traefik_certs:/certs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.ganjaking.cloud`)"
      # HTTP Routers
      - "traefik.http.routers.traefik-rtr.entrypoints=https"
      - "traefik.http.routers.traefik-rtr.rule=Host(`traefik.ganjaking.cloud`)"
      - "traefik.http.routers.traefik-rtr.service=api@internal"
      - "traefik.http.routers.traefik-rtr.priority=10"
      # HTTP-to-HTTPS Redirect
      - "traefik.http.routers.http-catchall.entrypoints=http"
      - "traefik.http.routers.http-catchall.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=USER:BASIC_AUTH_PASSWORD"
      ## Middlewares
      #- "traefik.http.routers.traefik-rtr.middlewares=chain-oauth@file"
      - "traefik.http.middlewares.traefik-headers.headers.accesscontrolallowmethods=GET, OPTIONS, PUT"
      - "traefik.http.middlewares.traefik-headers.headers.accesscontrolalloworiginlist=https://traefik.ganjaking.cloud"
      - "traefik.http.middlewares.traefik-headers.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.traefik-headers.headers.addvaryheader=true"
      - "traefik.http.middlewares.traefik-headers.headers.allowedhosts=traefik.ganjaking.cloud"
      - "traefik.http.middlewares.traefik-headers.headers.hostsproxyheaders=X-Forwarded-Host"
      - "traefik.http.middlewares.traefik-headers.headers.sslredirect=true"
      - "traefik.http.middlewares.traefik-headers.headers.sslhost=traefik.ganjaking.cloud"
      - "traefik.http.middlewares.traefik-headers.headers.sslforcehost=true"
      - "traefik.http.middlewares.traefik-headers.headers.sslproxyheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.traefik-headers.headers.stsseconds=63072000"
      - "traefik.http.middlewares.traefik-headers.headers.stsincludesubdomains=true"
      - "traefik.http.middlewares.traefik-headers.headers.stspreload=true"
      - "traefik.http.middlewares.traefik-headers.headers.forcestsheader=true"
      - "traefik.http.middlewares.traefik-headers.headers.framedeny=true"
      - "traefik.http.middlewares.traefik-headers.headers.contenttypenosniff=true"
      - "traefik.http.middlewares.traefik-headers.headers.browserxssfilter=true"
      - "traefik.http.middlewares.traefik-headers.headers.referrerpolicy=same-origin"
      - "traefik.http.middlewares.traefik-headers.headers.featurepolicy=camera 'none'; geolocation 'none'; microphone 'none'; payment 'none'; usb 'none'; vr 'none';"
      - "traefik.http.middlewares.traefik-headers.headers.customresponseheaders.X-Robots-Tag=none,noarchive,nosnippet,notranslate,noimageindex,"
      - "traefik.http.middlewares.traefik-headers.headers.customresponseheaders.X-Content-Type-Options=nosniff"
      ## API Forward Auth Bypass #
      - "traefik.http.routers.traefik-bypass.entrypoints=https"
      - "traefik.http.routers.traefik-bypass.rule=Host(`traefik.ganjaking.cloud`)"
      - "traefik.http.routers.traefik-bypass.middlewares=traefik-auth"
      - "traefik.http.routers.traefik-bypass.priority=20"
      - "traefik.http.routers.traefik-bypass.service=api@internal"
      - "traefik.http.routers.traefik-bypass.tls=true"
      - "traefik.http.routers.traefik-bypass.tls.certresolver=gcloud"
      - "traefik.http.routers.traefik-bypass.tls.domains[0].main=ganjaking.cloud"
      - "traefik.http.routers.traefik-bypass.tls.domains[0].sans=*.ganjaking.cloud"

networks:
    traefik_proxy:
      external: true
      attachable: true

volumes:
  traefik_data:
    driver: local-persist
    driver_opts:
      mountpoint: /opt/sync/dk/traefik_data