echo '
version: "3.9"

services:
  # Start the agent with the latest version
  hub-agent:
    hostname: hub-agent
    image: ghcr.io/traefik/hub-agent-traefik:v1.0.0
    pull_policy: always
    command:
      - run
      - --hub.token=2a481c21-4568-40a4-bbd5-5568116f0033
      - --auth-server.advertise-url=http://hub-agent
      - --traefik.host=traefik
      - --traefik.docker.swarm-mode
      - --traefik.tls.insecure=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 1

  # Start Traefik with the latest version
  traefik:
    hostname: traefik
    image: traefik:v2.8
    command:
      # Enable Hub communication (open the port 9900 and 9901 by default)
      - --experimental.hub=true
      - --hub.tls.insecure=true
      - --metrics.prometheus.addrouterslabels=true
    deploy:
      replicas: 1

' > ./docker-compose-hub-agent.yaml && docker stack deploy -c ./docker-compose-hub-agent.yaml hub-agent