version: '3.9'
#docker network create --driver overlay --opt encrypted --scope swarm --attachable  traefik-network
#docker secret create ganjaking-cloud.crt /opt/sync/dk/traefik_data/certs/ganjaking-cloud.crt
#docker secret create ganjaking-cloud.key /opt/sync/dk/traefik_data/certs/ganjaking-cloud.key

x-default-opts:
  &default-opts
  logging:
    options:
      max-size: "10m"

networks:
  traefik-network:
    external: true
    attachable: true

services:
  #created-in: portainer
  traefik:
    <<: *default-opts
    image: traefik:latest
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.name == unison-master]
      update_config:
        delay: 15s
        parallelism: 1
        monitor: 10s
        failure_action: rollback
        max_failure_ratio: 0.55
    networks:
      - traefik-network
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    command:
      - "--log.level=INFO"
      - "--accesslog=true"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--ping=true"
      - "--ping.entrypoint=ping"
      - "--entryPoints.ping.address=:8082"
      - "--entryPoints.http.address=:80"
      - "--entryPoints.https.address=:443"
      - "--providers.docker=true"
      - "--providers.docker.watch=true"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.swarmModeRefreshSeconds=15s"
      - "--providers.docker.network=traefik-network"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.file.filename=/etc/traefik/configs/traefik-dynamic-configuration.yml"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.buckets=0.1,0.3,1.2,5.0"
      - "--global.checkNewVersion=true"
      - "--global.sendAnonymousUsage=false"
      - "--log.filePath=/etc/traefik/log/traefik.log"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - /opt/sync/dk/traefik_data/acme/acme.json:/etc/traefik/acme/acme.json:rw
      - /opt/sync/dk/traefik_data/traefik-dynamic-configuration.yml:/etc/traefik/configs/traefik-dynamic-configuration.yml:rw
      - /opt/sync/dk/traefik_data/log/traefik.log:/etc/traefik/log/traefik.log
      - /opt/sync/dk/traefik_data/certs/:/etc/traefik/certs/
    healthcheck:
      test: ["CMD", "wget", "http://localhost:8082/ping", "--spider"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    labels:
      - "traefik.enable=true"
      # Traefik URL (replace with yours)
      - "traefik.http.routers.traefi.rule: Host(`traefik.ganjaking.cloud`)"
      - "traefik.http.routers.traefi.entrypoints: web"
      - "traefik.http.routers.traefi.middlewares: https_redirect"
      - "traefik.http.routers.traefik.rule: Host(`traefik.ganjaking.cloud`)"
      - "traefik.http.routers.traefik.entrypoints: websecure"
      - "traefik.http.routers.traefik.tls: true"
      - "traefik.http.middlewares.https_redirect.redirectscheme.scheme: https"
      - "traefik.http.middlewares.https_redirect.redirectscheme.permanent: true"

      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.stls.certresolver=letsencrypt"
      - "traefik.http.services.traefik.loadbalancer.passhostheader=true"
      - "traefik.http.routers.traefik.middlewares=authtraefik"
      - "traefik.http.middlewares.authtraefik.basicauth.users=traefikadmin:$$2y$$10$$sMzJfirKC75x/hVpiINeZOiSm.Jkity9cn4KwNkRvO7hSQVFc5FLO"



volumes:
  traefik_data:
    driver: local-persist
    driver_opts:
      mountpoint: /opt/sync/dk/traefik_data
  traefik_certs:
    driver: local-persist
    driver_opts:
      mountpoint: /opt/sync/dk/traefik_data/certs