version: '3.8'

services:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.name == unison-master]
        max_replicas_per_node: 1
    links:
      - pxc_galera
      - traefik_proxy
    volumes:
      #- /opt/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php:rw
      - phpmyadmin:/var/www/html:rw
    environment:
      PMA_HOST: pxc_percona-xtradb-master
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      PUID: "1001"
      PGID: "1001"
    restart: always
    ports:
      - "10053:80"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`ganjaking.asia/phpmyadmin`)"
      - "traefik.http.routers.traefik-secure.middlewares=chain-no-auth@file"
      - "traefik.http.routers.traefik-secure.service=api@internal"

volumes:
  phpmyadmin:
    driver: local-persist
    driver_opts:
      mountpoint: /opt/sync/dk/phpmyadmin

networks:
  default:
    external: true
    name: pxc_galera
  traefik:
    external: true
    name: traefik_proxy