version: '3.8'

services:

  redmine:
    image: 'bitnami/redmine:latest'
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.name == unison-master]
        max_replicas_per_node: 1
    links:
      - pxc_galera
    volumes:
      - redmine_data:/bitnami/redmine:rw
    ports:
      - "10054:8080"
      - "8443:8443"
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
      REDMINE_DATABASE_TYPE: "mariadb"
      REDMINE_DATABASE_HOST: ${REDMINE_DATABASE_HOST}
      REDMINE_DATABASE_USER: ${REDMINE_DATABASE_USER}
      REDMINE_DATABASE_PASSWORD: ${REDMINE_DATABASE_PASSWORD}
      REDMINE_DATABASE_NAME: "ganjaking_redmine"
      REDMINE_USERNAME: "admin"
      REDMINE_PASSWORD: ${REDMINE_PASSWORD}
      REDMINE_EMAIL: ${REDMINE_EMAIL}
      REDMINE_LANGUAGE: "en"

volumes:
  redmine_data:
    driver: local-persist
    driver_opts:
      mountpoint: /opt/sync/dk/redmine_data

networks:
  default:
    external: true
    name: pxc_galera