version: "3.7"
services:
  code-server:
    image: lscr.io/linuxserver/openvscode-server:latest
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.labels.name == unison-master ]
      labels:
        traefik.enable: "true"
        traefik.docker.network: "internet"
        traefik.http.routers.code-server.entrypoints: "https"
        traefik.http.routers.code-server.middlewares: "default@file"
        traefik.http.routers.code-server.rule: "Host(`cs.ganjaking.cloud`)"
        traefik.http.routers.code-server.tls.options: "modern@file"
        traefik.http.routers.code-server.tls: "true"
        traefik.http.services.code-server.loadbalancer.server.port: 3000
        traefik.http.services.code-server.loadbalancer.sticky.cookie.httpOnly: "true"
        traefik.http.services.code-server.loadbalancer.sticky.cookie.secure: "true"
    volumes:
      - cs_data:/config
    networks:
      - internet
    restart: unless-stopped
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Asia/Singapore
      - PASSWORD=${PASSWORD} #optional
      - SUDO_PASSWORD=${SUDO_PASSWORD} #optional

volumes:
  cs_data:
    driver: local-persist
    driver_opts:
      mountpoint: /opt/sync/db/cs_data
networks:
  internet:
    external: true
    attachable: true