---
# ansible-playbook -i configs/hosts debug-playbook-alpine.yml

- name: run discovery
  hosts: linode-prod
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - debug: var=ansible_host