version: '3.9'

services:

  redis-node-0:
    image: docker.io/bitnami/redis-cluster:6.2
    volumes:
      - redis-cluster_data-0:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-master'

  redis-node-1:
    image: docker.io/bitnami/redis-cluster:6.2
    volumes:
      - redis-cluster_data-1:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-master'

  redis-node-2:
    image: docker.io/bitnami/redis-cluster:6.2
    volumes:
      - redis-cluster_data-2:/bitnami/redis/data
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-master'

  redis-master:
    image: docker.io/bitnami/redis-cluster:6.2
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDISCLI_AUTH=bitnami'
      - 'REDIS_CLUSTER_REPLICAS=1'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-master'
      - 'REDIS_CLUSTER_CREATOR=yes'
    volumes:
      - redis-cluster_data-5:/bitnami/redis/data

  balancer:
    image: docker.io/bitnami/haproxy:2-debian-10
    container_name: haproxy
    deploy:
      replicas: 1
      mode: global
      placement:
        constraints:
          - node.role == manager
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2
      - redis-master
    restart: always
    ports:
      - '80:80'
      - '443:443'
      - '9000:9000'
    networks:
      - pres-tier
    volumes:
      - './configs/haproxy.cfg:/bitnami/haproxy/conf/haproxy.cfg'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - 'haproxy_data:/var/log/haproxy'
      - './errors/400.http:/etc/haproxy/errors/400.http'
      - './errors/403.http:/etc/haproxy/errors/403.http'
      - './errors/408.http:/etc/haproxy/errors/408.http'
      - './errors/500.http:/etc/haproxy/errors/500.http'
      - './errors/502.http:/etc/haproxy/errors/502.http'
      - './errors/503.http:/etc/haproxy/errors/503.http'
      - './errors/504.http:/etc/haproxy/errors/504.http'

  prometheus:
    image: docker.io/bitnami/prometheus:2-debian-10
    container_name: prometheus
    deploy:
      replicas: 1
      mode: global
      placement:
        constraints:
          - node.role == manager
    restart: always
    ports:
      - '10052:10052'
    networks:
      - pres-tier
    volumes:
      - ./configs/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml

volumes:
  redis_master_data:
    driver: local
  redis_node0_data:
    driver: local
  redis_node1_data:
    driver: local
  redis-cluster_data-0:
    driver: local
  redis-cluster_data-1:
    driver: local
  redis-cluster_data-2:
    driver: local
  redis-cluster_data-3:
    driver: local
  redis-cluster_data-4:
    driver: local
  redis-cluster_data-5:
    driver: local

networks:
  pres-tier:
    driver: bridge
  app-tier:
    driver: bridge
  data-tier:
    driver: bridge

secrets:
  redis_auth_password: # echo "mysupersecretpassword" | docker secret create redis_auth_password -
    file: ./secret/auth_password.txt
  redis_master_password: # echo "mysupersecretpassword" | docker secret create redis_master_password -
    file: ./secret/master_password.txt
  redis_password: # echo "mysupersecretpassword" | docker secret create redis_password -
    file: ./secret/redis_password.txt
