version: '3'
services:

  glusterfs1:
    image: gluster/gluster-centos
    privileged: true
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.labels.name == unison-master ]
        max_replicas_per_node: 1
    networks:
      - glusterfs2
    environment:
      - PUID:1001
      - PGID:1001
    volumes:
      - glusterfs_etc_1:/etc/glusterfs
      - glusterfs_lib_1:/var/lib/glusterd
      - glusterfs_log_1:/var/log/glusterfs
      - gulsterfs_data_1:/data/glusterfs

  glusterfs2:
    image: gluster/gluster-centos
    privileged: true
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.labels.name == unison-node-0 ]
        max_replicas_per_node: 1
    networks:
     - glusterfs
    environment:
      - PUID:1001
      - PGID:1001
    volumes:
      - glusterfs_etc_2:/etc/glusterfs
      - glusterfs_lib_2:/var/lib/glusterd
      - glusterfs_log_2:/var/log/glusterfs
      - gulsterfs_data_2:/data/glusterfs
  
  glusterfs3:
    image: gluster/gluster-centos
    privileged: true
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.labels.name == unison-node-1 ]
        max_replicas_per_node: 1
    networks:
      - glusterfs
    volumes:
      - glusterfs_etc_3:/etc/glusterfs
      - glusterfs_lib_3:/var/lib/glusterd
      - glusterfs_log_3:/var/log/glusterfs
      - gulsterfs_data_3:/data/glusterfs
  
  glusterfs4:
    image: gluster/gluster-centos
    privileged: true
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.labels.name == unison-node-2 ]
        max_replicas_per_node: 1
    networks:
      - glusterfs
    volumes:
      - glusterfs_etc_4:/etc/glusterfs
      - glusterfs_lib_4:/var/lib/glusterd
      - glusterfs_log_4:/var/log/glusterfs
      - gulsterfs_data_4:/data/glusterfs

networks:
  glusterfs: 
    driver: overlay
    attachable: true

volumes:
  glusterfs_etc_1:
    driver: local-persist
    driver_opts: 
      mountpoint: /opt/glusterfs/etc
  glusterfs_lib_1:
    driver: local-persist
    driver_opts: 
      mountpoint: /opt/glusterfs/lib
  glusterfs_log_1:
    driver: local-persist
    driver_opts:
      mountpoint: /opt/glusterfs/log
  gulsterfs_data_1:
    driver: local-persist
    driver_opts:
      mountpoint: /opt/glusterfs/db
  
  glusterfs_etc_2:
    driver: local-persist
    driver_opts: 
      mountpoint: /opt/glusterfs/etc
  glusterfs_lib_2:
    driver: local-persist
    driver_opts: 
      mountpoint: /opt/glusterfs/lib
  glusterfs_log_2:
    driver: local-persist
    driver_opts:
      mountpoint: /opt/glusterfs/log
  gulsterfs_data_2:
    driver: local-persist
    driver_opts:
      mountpoint: /opt/glusterfs/db

  glusterfs_etc_3:
    driver: local-persist
    driver_opts:
      mountpoint: /opt/glusterfs/etc
  glusterfs_lib_3:
    driver: local-persist
    driver_opts:
      mountpoint: /opt/glusterfs/lib
  glusterfs_log_3:
    driver: local-persist
    driver_opts:
      mountpoint: /opt/glusterfs/log
  gulsterfs_data_3:
    driver: local-persist
    driver_opts:
      mountpoint: /opt/glusterfs/db

  glusterfs_etc_4:
    driver: local-persist
    driver_opts:
      mountpoint: /opt/glusterfs/etc
  glusterfs_lib_4:
    driver: local-persist
    driver_opts:
      mountpoint: /opt/glusterfs/lib
  glusterfs_log_4:
    driver: local-persist
    driver_opts:
      mountpoint: /opt/glusterfs/log
  gulsterfs_data_4:
    driver: local-persist
    driver_opts:
      mountpoint: /opt/glusterfs/db


# docker-compose up -d glusterfs1 glusterfs2 glusterfs3 glusterfs4
# echo "Sleep 10 seconds to wait the glusterfs up"
# sleep 10
# docker-compose exec glusterfs1 gluster peer probe glusterfs2 glusterfs3 glusterfs4
# docker-compose exec glusterfs1 gluster volume create test-volume replica 2 transport tcp glusterfs1:/data/glusterfs/test glusterfs2:/data/glusterfs/test
# docker-compose exec glusterfs1 gluster volume start test-volume
# docker-compose exec glusterfs1 setfacl -m u:1001:rwx /data/glusterfs/test
# docker-compose exec glusterfs2 setfacl -m u:1001:rwx /data/glusterfs/test
# docker-compose exec glusterfs1 tail -f /var/log/glusterfs/bricks/data-glusterfs-test.log