version: '3'
services:

  glusterfs1:
    image: gluster/gluster-centos
    privileged: true
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.labels.name == unison-master ]
        max_replicas_per_node: 1
    networks:
      - glusterfs2
      - internet
    environment:
      - PUID:1001
      - PGID:1001
    volumes:
      - glusterfs_etc_1:/etc/glusterfs
      - glusterfs_lib_1:/var/lib/glusterd
      - glusterfs_log_1:/var/log/glusterfs
      - gulsterfs_data_1:/data/glusterfs

  glusterfs2:
    image: gluster/gluster-centos
    privileged: true
    networks:
     - glusterfs
     - internet
    environment:
      - PUID:1001
      - PGID:1001
    volumes:
      - glusterfs_etc_volume2:/etc/glusterfs
      - glusterfs_lib_volume2:/var/lib/glusterd
      - glusterfs_log_volume2:/var/log/glusterfs
      - gulsterfs_data_volume2:/data/glusterfs
  
  glusterfs3:
    image: gluster/gluster-centos
    privileged: true
    networks:
      - glusterfs
      - internet
    volumes:
      - glusterfs_etc_volume3:/etc/glusterfs
      - glusterfs_lib_volume3:/var/lib/glusterd
      - glusterfs_log_volume3:/var/log/glusterfs
      - gulsterfs_data_volume3:/data/glusterfs
  
  glusterfs4:
    image: gluster/gluster-centos
    privileged: true
    networks:
      - glusterfs
      - internet
    volumes:
      - glusterfs_etc_volume3:/etc/glusterfs
      - glusterfs_lib_volume3:/var/lib/glusterd
      - glusterfs_log_volume3:/var/log/glusterfs
      - gulsterfs_data_volume3:/data/glusterfs

networks:
  glusterfs: 
    driver: overlay
    attachable: true
  internet: 
    external: true
    attachable: true

volumes:
  glusterfs_etc_1:
    driver_opts: 
    mountpoint: /opt/glusterfs/etc
  glusterfs_lib_1:
    driver_opts: 
    mountpoint: /opt/glusterfs/lib
  glusterfs_log_1:
    driver_opts:
    mountpoint: /opt/glusterfs/log
  gulsterfs_data_1:
    driver_opts:
    mountpoint: /opt/glusterfs/db
  
  glusterfs_etc_volume2:
  glusterfs_lib_volume2:
  glusterfs_log_volume2:
  gulsterfs_data_volume2:

  glusterfs_etc_volume3:
  glusterfs_lib_volume3:
  glusterfs_log_volume3:
  gulsterfs_data_volume3:

  glusterfs_etc_volume4:
  glusterfs_lib_volume4:
  glusterfs_log_volume4:
  gulsterfs_data_volume4:

# docker-compose up -d glusterfs1 glusterfs2 glusterfs3 glusterfs4
# echo "Sleep 10 seconds to wait the glusterfs up"
# sleep 10
# docker-compose exec glusterfs1 gluster peer probe glusterfs2
# docker-compose exec glusterfs1 gluster volume create test-volume replica 2 transport tcp glusterfs1:/data/glusterfs/test glusterfs2:/data/glusterfs/test
# docker-compose exec glusterfs1 gluster volume start test-volume
# docker-compose exec glusterfs1 setfacl -m u:1000:rwx /data/glusterfs/test
# docker-compose exec glusterfs2 setfacl -m u:1000:rwx /data/glusterfs/test
# docker-compose exec glusterfs1 tail -f /var/log/glusterfs/bricks/data-glusterfs-test.log