---
# ansible-playbook -i configs/hosts playbook-alp.yml

- name: run tasks on all hosts
  hosts: linode-prod
  become: true
  tasks:

    - name: upgrade all packages (apk)
      apk:
        available: yes
        update_cache: yes
        state: latest
        upgrade: yes