---
# ansible-playbook -i configs/hosts playbook.yml

- name: run tasks on all hosts
  hosts: debian-test
  become: true
  tasks:
    - name: update cache on all servers
      apt:
        name: "*"
        state: latest
        update_cache: yes
        cache_valid_time: 3600
        force_apt_get: yes

    - name: upgrade all dist-packages
      apt:
        name: "*"
        state: latest
        upgrade: dist
        cache_valid_time: 3600
        force_apt_get: yes

    - name: install pre-requisites
      apt:
        name:
          - neofetch
          - nano
        state: present
        update_cache: true
        cache_valid_time: 3600
        force_apt_get: yes