---
# ansible-playbook -i configs/hosts playbook.yml

- name: run tasks on all hosts
  hosts: alpine-test
  become: true
  tasks:

    - name: upgrade all packages (apk)
      apk:
        available: yes
        update_cache: yes
        state: latest
        upgrade: yes
        cache_valid_time: 3600