---
# ansible-playbook -i configs/hosts playbook.yml

- name: run tasks on all hosts
  hosts: debian-prod
  become: true
  tasks:
    - name: Add Apt signing key from official docker repo
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Add Apt signing key from gluster repo
      apt_key:
        url: 'https://download.gluster.org/pub/gluster/glusterfs/{{ glusterfs_gpg_key_version }}/rsa.pub'
        state: present

    - name: add docker official repository for Debian Stretch
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian bullseye stable
        state: present

    - name: add glusterfs offical repository for Debian Bullseye
      apt_repository:
        repo: deb [arch=amd64] https://download.gluster.org/pub/gluster/glusterfs/10/LATEST/Debian/bullseye/amd64/apt bullseye main
        state: present

    - name: update cache on all servers
      apt:
        name: "*"
        state: latest
        update_cache: yes
        cache_valid_time: 3600
        force_apt_get: yes

    - name: install pre-requisites
      apt:
        name:
          - glusterfs-server
          - glusterfs-client
          - git
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - neofetch
          - nano
          - gcc
          - g++
          - make
          - flex
          - bison
          - openssl
          - libssl-dev
          - perl
          - perl-base
          - perl-modules
          - libperl-dev
          - libperl4-corelibs-perl
          - libwww-perl
          - libaio1
          - libaio-dev
          - zlib1g
          - zlib1g-dev
          - libcap-dev
          - cron
          - bzip2
          - zip
          - automake
          - autoconf
          - libtool
          - cmake
          - pkg-config
          - python
          - libdb-dev
          - libsasl2-dev
          - libncurses5
          - libncurses5-dev
          - libsystemd-dev
          - bind9
          - dnsutils
          - quota
          - patch
          - logrotate
          - rsyslog
          - libc6-dev
          - libexpat1-dev
          - libcrypt-openssl-rsa-perl
          - libnuma-dev
          - libnuma1
          - curl
          - apt-transport-https
          - ca-certificates
          - gnupg
          - gnupg2
          - apt-utils
          - lsb-release
        state: present
        update_cache: true
        cache_valid_time: 3600
        force_apt_get: yes

- name: reboot required?
  hosts: debian-test
  become: true
  tasks:
    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Prompt for rebooting
      pause:
        prompt: "Press ENTER to reboot {{ item }} now, or Ctrl+C to abort."
      when: "'reboot_required_file' in hostvars[item] and hostvars[item]['reboot_required_file'].stat.exists"
      with_items: "{{ play_hosts }}"

    - name: Rebooting machine
      shell: sleep 2 && shutdown -r now "Ansible updates triggered"
      async: 1
      poll: 0
      ignore_errors: true
      when: reboot_required_file.stat.exists

    - name: Waiting for the machine to come back
      local_action: wait_for host={{ ansible_host }} state=started port=22 delay=30
      become: no
      when: reboot_required_file.stat.exists