---
# Singapore IM8 Compliance Mapping - Alpine Linux Hardening
# Version: IM8 v4.0 (2023)
# Applies when: 'sg_regulated: true' in host vars

controls:
  - id: "IM8-4.1"
    title: "System Hardening Baseline"
    mappings:
      cis: ["1.1", "3.1", "4.1"]
      nist: ["AC-6", "CM-6"]
    tasks:
      - tasks/01_preflight.yml
      - tasks/02_minimal_install.yml
      - tasks/03_kernel_hardening.yml
    audit: |
      # Check for unnecessary packages
      apk info | grep -vE '(openssl|ca-certificates|busybox)'
      # Verify kernel hardening
      sysctl -a | grep -E '(kernel.yama.ptrace_scope|kernel.kptr_restrict)'

  - id: "IM8-4.3"
    title: "Authentication Controls"
    mappings:
      cis: ["5.1", "5.2"]
      nist: ["IA-2", "IA-5"]
    tasks:
      - tasks/05_user_auth.yml
      - templates/etc/ssh/sshd_config.j2
    audit: |
      grep -E '^(PasswordAuthentication|ChallengeResponseAuthentication)' /etc/ssh/sshd_config
      awk -F: '($2 == "" ) { print $1 }' /etc/shadow

  - id: "IM8-6.2"
    title: "Audit Logging"
    mappings:
      cis: ["4.1.5", "4.1.6"]
      disa_stig: ["AU-3", "AU-12"]
    tasks:
      - tasks/07_logging.yml
      - templates/etc/audit/rules.d/im8.j2
    audit: |
      rc-service auditd status | grep -q 'started'
      ausearch -k im8_audit | head -5

  - id: "IM8-8.4"
    title: "Network Security"
    mappings:
      cis: ["3.2", "3.3"]
      nist: ["SC-7", "SC-8"]
    tasks:
      - tasks/08_network.yml
    audit: |
      iptables -L -n -v | grep -E '(DROP|REJECT)'
      netstat -tuln | grep -vE '(127.0.0.1|::1)'

profiles:
  - name: "essential"
    description: "IM8 Essential Requirements (Tier 1)"
    includes: ["IM8-4.1", "IM8-4.3"]

  - name: "enhanced"
    description: "IM8 Enhanced Controls (Tier 2)"
    includes: ["IM8-4.1", "IM8-4.3", "IM8-6.2"]

  - name: "financial"
    description: "MAS-TRM + IM8 Requirements (Tier 3)"
    includes: "*"

metadata:
  source: "IM8 v4.0 (2023)"
  authority: "CSA Singapore"
  applies_to: "Government Financial Systems"
  relationships:
    cis: "v8.0"
    mas_trm: "2023 Edition"
  notes: |
    Required for Singapore government systems:
    ansible-playbook site.yml -e "sg_regulated=true im8_profile=enhanced"
