---
# Production environment variables (high security)
# For development environments
# ansible-playbook site.yml -e "@vars/development.yml"

# # For production environments
# ansible-playbook site.yml -e "@vars/production.yml"

security_level: high
enable_fips: true
audit_profile: full
ssh_permit_root_login: "no"
password_auth: false
minimum_uid: 1000
cis_profile: server
im8_profile: enhanced
enable_selinux: true
docker_restrictions: hardened

# Package management
required_packages:
  - audit
  - sudo
  - fail2ban
  - openssh-server
  - libselinux
  - haveged

# Network settings
network_hardening:
  disable_ipv6: true
  firewall_profile: restrictive
  tcp_strong_iss: true
  syn_cookies: true
  rp_filter: strict

# Crypto policies
crypto_policy:
  min_rsa_size: 3072
  ssh_algorithms:
    kex: curve25519-sha256
    hostkey: ssh-ed25519,rsa-sha2-512
    cipher: chacha20-poly1305@openssh.com,aes256-gcm@openssh.com
    mac: hmac-sha2-512-etm@openssh.com
