---
- name: Provision Alpine Linux cluster
  hosts: alpine_cluster
  become: true
  gather_facts: false # Alpine requires explicit setup

  tasks:
    - name: Ensure python3 is present
      raw: apk add python3
      changed_when: false
      register: python_install
      until: python_install is succeeded

  roles:
    - role: alpine_base
      tags: always

    - role: user_admin
      tags: users

    - role: alpine_hardening
      tags: security

    - role: docker_ce
      tags: docker
      when: "'docker' in group_names" # Optional conditional
