version: "3.8"

services:
  portainer:
    image: portainer/portainer-ce:2.27.4
    container_name: portainer
    command:
      - --http-disabled
      - -H tcp://tasks.agent:9001
      - --tlsskipverify
    ports:
      - "127.0.0.1:9000:9000" # Localhost binding for NPM
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - PORTAINER_AGENT_SECRET=${AGENT_SECRET}
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider http://localhost:9000/api/status || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s # Added initialization grace period
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true" # Added log compression
    security_opt:
      - no-new-privileges:true
    cap_drop: # Added capability restrictions
      - ALL
    networks:
      - portainer_net
      - npm_network

  agent:
    image: portainer/agent:2.27.4
    container_name: portainer_agent
    hostname: "${HOSTNAME}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/volumes:/var/lib/docker/volumes:ro
    environment:
      - AGENT_SECRET=${AGENT_SECRET}
      - EDGE=1
      - EDGE_ID=${EDGE_ID:-$(hostname)} # Added edge identification
    ports:
      - "9001:9001" # Agent port
    networks:
      - portainer_net
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop: # Added capability restrictions
      - ALL
    cap_add: # Minimal required capabilities
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID

volumes:
  portainer_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/portainer_data
    labels: # Added volume labels
      - "backup=true"
      - "retention=30d"

networks:
  portainer_net:
    driver: bridge
    enable_ipv6: false
    attachable: false # Enhanced isolation
  npm_network:
    external: true
    name: npm_network # Explicit network naming
