entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"

http:
  routers:
    traefik:
      rule: "Host(`traefik.ganjaking.cloud`)"  && Path(`/traefik/`)"
      service: traefik-service
      tls:
        options: myTLSOptions

tls:
  certificates:
    - certFile: /opt/sync/dk/traefik_data/certs/ganjaking-cloud.crt
      keyFile: /opt/sync/dk/traefik_data/certs/ganjaking-cloud.key
      stores:
        default:
          defaultCertificate:
            certFile: /opt/sync/dk/traefik_data/certs/ganjaking-cloud.crt
            keyFile: /opt/sync/dk/traefik_data/certs/ganjaking-cloud.key
  options:
    myTLSOptions:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256