http:
 #region routers
  routers:
    traefik:
      entryPoints:
        - "https"
      rule: "Host(`traefik.ganjaking.cloud`)"
      middlewares:
        - default-headers
      tls: {
             certificates:
               - certFile: /run/secrets/ganjaking-cloud.crt
                 keyFile: /run/secrets/ganjaking-cloud.key
      }
      service: traefik

#endregion
#region services
  services:

    #syncthing:
      #loadBalancer:
       # servers:
       #   - url: "https://192.168.0.103:8384"
       # passHostHeader: true

#endregion
  middlewares:
    https-redirect:
      redirectScheme:
        scheme: https

    default-headers:
      headers:
        accessControlAllowMethods: "GET, OPTIONS, PUT"
        accesscontrolMaxAge: 100
        hostsProxyHeaders: "X-Forwarded-Host"
        frameDeny: true
        sslRedirect: true
        sslForceHost: true
        browserXssFilter: true
        contentTypeNoSniff: true
        referrerPolicy: "same-origin"
        featurePolicy: "camera 'none'; geolocation 'none'; microphone 'none'; payment 'none'; usb 'none'; vr 'none';"
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https
        customResponseHeaders:
          X-Robots-Tag: "one,noarchive,nosnippet,notranslate,noimageindex,"
          X-Content-Type-Options: "noSniff"

    secured:
      chain:
        middlewares:
        - default-whitelist
        - default-headers