http:
  routers:
    traefik:
      rule: "Host(`traefik.ganjaking.cloud`)"
      service: traefik
      tls:
        options: myTLSOptions

tls:
  certificates:
    - certFile: /run/secrets/ganjaking-cloud.crt
      keyFile: /run/secrets/ganjaking-cloud.key
  options:
    myTLSOptions:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256