global:
  scrape_interval: 30s
  external_labels:
    monitor: 'cluster-nodes'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter-master:9100', 'node-exporter-node-0:9100', 'node-exporter-node-1:9100']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor-master:8080', 'cadvisor-node-0:8080', 'cadvisor-node-1:8080']
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']