###############################################################
#                   Authelia configuration                    #
###############################################################

host: 0.0.0.0
port: 9091
log_level: warn

jwt_secret: ${AUTHELIA_JWT_SECRET_FILE}
default_redirection_url: https://authelia.example.com

totp:
  issuer: authelia.com
  period: 30
  skew: 1

authentication_backend:
  file:
    path: /config/users_database.yml
    # customize passwords based on https://docs.authelia.com/configuration/authentication/file.html
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 512 # blocks this much of the RAM. Tune this

access_control:
  default_policy: deny
  rules:
    - domain: authelia.example.com
      policy: bypass
    - domain: "*.ganjaking.cloud"
        policy: two_factor
    - domain: "ganjaking.cloud"
        policy: two_factor

session:
  name: gjk_authelia_session
  expiration: 3600
  inactivity: 300
  domain: ganjaking.cloud

redis:
  host: redis_redis-master
  port: 6379
  password: ${AUTHELIA_SESSION_REDIS_PASSWORD_FILE}

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  mysql:
    host: ${MYSQL_HOST}
    port: 3306
    database: authelia
    username: ganjaking
    password: ${AUTHELIA_STORAGE_MYSQL_PASSWORD_FILE}

notifier:
  smtp:
    username: ${SMTP_USERNAME}
    host: smtp.gmail.com
    port: 587
    sender: ${SMTP_USERNAME}
