###############################################################
#                   Authelia configuration                    #
###############################################################


theme: dark #light/dark


# This secret can also be set using the env variables AUTHELIA_JWT_SECRET_FILE
# I used this site to generate the secret: https://www.grc.com/passwords.htm
# jwt_secret: SECRET_GOES_HERE # use docker secret file instead AUTHELIA_JWT_SECRET_FILE
jwt_secret: "Txf9Ml6UZy2cuzOW+Wk3oofCf4x5AaXR7aXmRJZiKey59kSt4lQoEwYrmwHKhZZT8Fe+vkTcrS25lqVzfHcZdLGsmHMS3yxsduUoxtciQ4zXFJDfcsiTWt4TDAf2Y2/aXVosA=="
# https://docs.authelia.com/configuration/miscellaneous.html#default-redirection-url
default_redirection_url: https://google.com/

server:
  host: 0.0.0.0
  port: 9091
  path: ""
  buffers:
    read: 4096
    write: 4096
  enable_pprof: false
  enable_expvars: false
  disable_healthcheck: false
  tls:
    key: ""
    certificate: ""

log:
  level: debug
  format: text
  file_path: /config/authelia.log

totp:
  issuer: ganjaking.cloud
  period: 30
  skew: 1

# Enable the following for Duo Push Notification support
# https://www.authelia.com/docs/features/2fa/push-notifications.html
#duo_api:
#  hostname: api-123456789.example.com
#  integration_key: ABCDEF
#  # This secret can also be set using the env variables AUTHELIA_DUO_API_SECRET_KEY_FILE
#  secret_key: # use docker secret file instead AUTHELIA_DUO_API_SECRET_KEY_FILE

authentication_backend:
  password_reset:
    disable: true
  refresh_interval: 5m
  file:
    path: /config/users_database.yml #this is where your authorized users are stored
    password:
      algorithm: argon2id
      iterations: 1
      key_length: 32
      salt_length: 16
      memory: 1024
      parallelism: 8

# https://docs.authelia.com/configuration/access-control.html
access_control:
  default_policy: deny
  rules:
    - domain: "auth.ganjaking.cloud"
      policy: bypass
    - domain: "ganjaking.cloud"
      policy: bypass
    - domain: "traefik.ganjaking.cloud"
      policy: one_factor
    - domain: "whoami.ganjaking.cloud"
      policy: one_factor

session:
  name: authelia_session
  secret: "3YS2uzz6ZN/e6ibkSZP0cOxb4AgqzgRAVZKTURW7t3+WsA81zJ+5v8QTIk7uMg5aUeAirPv0lgSJ2KLJaekokHBkyOqI5hVNbEYB21AwVbM3AVgilWyWObCp2sq3hdEEmAuhgw=="
  expiration: 3600 # 1 hour
  inactivity: 300 # 5 minutes
  domain: ganjaking.cloud # Should match whatever your root protected domain is

    # Optional. Can improve performance on a busy system. If not enabled, session info is stored in memory.
    #  redis:
    #    host: redis
    #    port: 6379
    # This secret can also be set using the env variables AUTHELIA_SESSION_REDIS_PASSWORD_FILE
  # password: authelia

regulation:
  max_retries: 3
  find_time: 10m
  ban_time: 24h

storage:
  # For local storage, uncomment lines below and comment out mysql. https://docs.authelia.com/configuration/storage/sqlite.html
  encryption_key: "j+roj7w42FYAIqVPlmhxAfL4RBU"
  local:
    path: /config/db.sqlite3

  #mysql:
  #  # MySQL allows running multiple authelia instances. Create database and enter details below.
  #  host: MYSQL_HOST
  #  port: 3306
  #  database: authelia
  #  username: DBUSERNAME
  #  # Password can also be set using a secret: https://docs.authelia.com/configuration/secrets.html
  #  # password: use docker secret file instead AUTHELIA_STORAGE_MYSQL_PASSWORD_FILE

notifier:
  #smtp:
  #  username: richard.irwanshah@gmail.com
  #  # This secret can also be set using the env variables AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
  #  # password: # use docker secret file instead AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
  #  host: SMTP_HOST
  #  port: 587 #465
  #  sender: richard.irwanshah@gmail.com
  # For testing purpose, notifications can be sent in a file. Be sure map the volume in docker-compose.
  filesystem:
    filename: /tmp/authelia/notification.txt
