###############################################################
#                         Users Database                      #
###############################################################

users:
  admin:
    displayname: "admin"
    password: "$argon2id$v=19$m=65536,t=3,p=4$0xM4mVx79bgua25rSxeUVg$/z8BJp2J1jYqZf2U5Fb6it4l3ebER7tkAG27Sbq4kEo"
    email: richard.irwanshah@gerekper.asia
    groups:
      - admins
      - dev