###############################################################
#                         Users Database                      #
###############################################################

users:
  admin:
    displayname: "admin"
    password: "admin:$argon2i$v=19$m=65536,t=4,p=1$ODhyTjRIU2pCUXdwLkVrQQ$25Us101h13Xkfq8erDRCVK5yPSar6f7szZa0vRyEjII"
    email: richard.irwanshah@gerekper.asia
    groups:
      - admins