[http.middlewares]
    [http.middlewares.authelia.forwardAuth]
        address = "http://traefik_authelia:9091/api/verify?rd=https://authelia.ganjaking.cloud"
        trustForwardHeader = true
        authResponseHeaders = ["Remote-User", "Remote-Groups"]
