[[tls.certificates]] #first certificate
    certFile = "certs/ganjaking.cloud.cert"
    keyFile = "certs/ganjaking.cloud.key"

[tls.stores]
    [tls.stores.default]
        [tls.stores.default.defaultCertificate]
            certFile = "certs/ganjaking.cloud.cert"
            keyFile = "certs//ganjaking.cloud.key"