---
# inventory/production/hosts.yml
all:
  vars:
    ansible_user: "hardener"
    ansible_ssh_private_key_file: "~/.ssh/alpine_hardening_key"
    ansible_become: true
    hardening_level: "high"
    compliance:
      cis: "hardened"
      im8: "enhanced"
      nist: "moderate"

  children:
    alpine_servers:
      hosts:
        web01:
          ansible_host: "192.168.1.10"
          docker_required: false
        web02:
          ansible_host: "192.168.1.11"
          docker_required: false

    container_hosts:
      hosts:
        docker01:
          ansible_host: "192.168.1.20"
          docker_required: true
          docker_config:
            icc: false
            userns_remap: "dockremap"
        docker02:
          ansible_host: "192.168.1.21"
          docker_required: true
          docker_config:
            icc: false
            userns_remap: "dockremap"

    high_security:
      hosts:
        db01:
          ansible_host: "192.168.1.30"
          hardening_level: "strict"
          enable_fips: true
          compliance:
            cis: "l2"
            im8: "financial"
            nist: "high"
